# Generated by Django 4.2.13 on 2024-05-30 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('descr_task', models.TextField()),
                ('date_begin', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('term', models.IntegerField(default=0)),
                ('source', models.TextField(blank=True, null=True)),
                ('descr_source', models.TextField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('1', 'Низкая степень важности'), ('2', 'Средняя степень важности'), ('3', 'Высокая степень важности')], max_length=50)),
                ('date_develop', models.DateTimeField()),
                ('date_funding', models.DateTimeField()),
                ('cost', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('1', 'Отложена'), ('2', 'В работе'), ('3', 'Завершена')], max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.company')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.division')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.facility')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.field')),
                ('last_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasker.task')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.license')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('defining', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defining', to='tasker.task', verbose_name='Определяющая задача')),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent', to='tasker.task', verbose_name='Зависимая задача')),
            ],
        ),
    ]
