# Generated by Django 4.2.13 on 2024-06-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskdependencies',
            options={'verbose_name': 'Зависимость задачи', 'verbose_name_plural': 'Зависимости задач'},
        ),
    ]
