# Generated by Django 4.2.13 on 2024-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_alter_task_options_alter_taskdependencies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_begin',
            field=models.DateTimeField(),
        ),
    ]
