# Generated by Django 4.2.13 on 2024-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_alter_task_date_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_develop',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_funding',
            field=models.DateField(),
        ),
    ]
