# Generated by Django 4.2.13 on 2024-07-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_alter_task_date_begin_alter_task_date_develop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('Низкая степень важности', 'Низкая степень важности'), ('Средняя степень важности', 'Средняя степень важности'), ('Высокая степень важности', 'Высокая степень важности')], max_length=50),
        ),
    ]
