# Generated by Django 4.2.13 on 2024-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0006_alter_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_develop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_funding',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Отложена', 'Отложена'), ('В работе', 'В работе'), ('Завершена', 'Завершена')], max_length=50),
        ),
    ]
