# Generated by Django 4.2.13 on 2024-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0008_remove_task_user_task_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
