# Generated by Django 4.2.13 on 2024-09-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0011_documenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
