# Generated by Django 4.2.13 on 2024-05-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Компания', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_employee_company', to='structure.company', verbose_name='Компания'),
        ),
    ]
