# Generated by Django 4.2.13 on 2024-08-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Загрузите документ', upload_to='comments/'),
        ),
    ]
