# Generated by Django 4.2.13 on 2024-08-21 08:58

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_document_options_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
