# Generated by Django 4.2.13 on 2024-08-21 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_comment_full_name_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=ckeditor.fields.RichTextField(help_text='Полный комментарий', verbose_name='Полный комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=ckeditor.fields.RichTextField(help_text='Краткие сведения', verbose_name='Краткие сведения'),
        ),
    ]
