# Generated by Django 4.2.13 on 2024-08-21 13:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_full_name_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='full_name',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Полный комментарий', verbose_name='Полный комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Краткие сведения', verbose_name='Краткие сведения'),
        ),
    ]
